# Netlify의 재작성(rewrite) 규칙을 설정합니다.
[[redirects]]
  # 우리 사이트의 /api/ 로 시작하는 모든 경로를
  from = "/api/*"
  
  # 실제 API 서버의 해당 경로로 대신 요청합니다.
  to = "https://oapi.koreaexim.go.kr/:splat"
  
  # 상태 코드 200은 '성공'을 의미하며, 페이지를 이동시키는 대신
  # 뒤에서 조용히 데이터를 가져오는 프록시 역할을 하도록 만듭니다. (가장 중요!)
  status = 200
  
  # 다른 규칙보다 이 규칙을 우선적으로 강제 적용합니다.
  force = true